version: '3.8'
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'restapi'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'Aa@123456'
    volumes:
      - ./data/sql/restapi.sql:/docker-entrypoint-initdb.d/restapi.sql
    ports:
      - '3308:3306'
    networks:
      - restapi-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  application:
    image: app
    container_name: restapi-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - restapi-network
    depends_on:
      - "db"
networks:
  restapi-network:
    name: restapi-network
    driver: bridge
