name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: ktlint
          uses: ScaCap/action-ktlint@master
          with:
            github_token: ${{ secrets.github_token }}
            reporter: github-pr-review # Change reporter

      - name: Set up JDK
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'
